version: '3.8'

services:
  bharatx-app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - GROQ_API_KEY=${GROQ_API_KEY}
    volumes:
      - ./.env.local:/app/.env.local:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/fetch-prices"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 